### ISSUE TITLE
Question about the api key

### ISSUE THREAD

**Issue by geeksilva97** [luisromeroaraya/metaltravelguide#1]
Where did you get the API key you're using in this [project](https://github.com/luisromeroaraya/metaltravelguide/blob/b8f4eb859968ca799c9b06e3007ee8902f650d35/frontend/src/index.html#L9)?

Just curious about it 🤔 . It's mine.

**Comment by luisromeroaraya** [comment]
Hi Edi, I found it on a youtube tutorial, not sure though in which of all
the videos because I saw many of them. Would you like me to change it? It
has helped me a lot to learn, greetings!

**Comment by luisromeroaraya** [comment]
Hey @geeksilva97 I just wanted to say sorry if I caused you any trouble using [this](https://github.com/geeksilva97/angular-map-application) API key without asking, I have already learned how to get one of my own from the Google platform. Thanks again for sharing your videos, they are really useful ;)

**Comment by abarbosa-godaddy** [comment]
Hey, it was not a problem at all. I was just curious. And I wanted to notify you I deleted that key. Cool.
